name: agendapro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.3.0
  firebase_database: ^10.4.0
  firebase_storage: ^11.5.5
  cloud_firestore: ^4.17.5
  flutter_facebook_auth: ^7.1.1
  cpf_cnpj_validator: ^2.0.0
  shared_preferences: ^2.1.1
  http: ^1.2.2
  image_picker: ^1.0.5
  cached_network_image: ^3.2.3
  smooth_page_indicator: ^1.1.0
  the_apple_sign_in: ^1.1.1
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  url_launcher: ^6.1.6
  file_picker: ^5.2.2
  progress_dialog:
    git:
      url: https://github.com/mostafaAbdelazim/progress_dialog.git

  # Icons para iOS
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: android/app/src/main/ic_launcher-playstore.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/welcome_image.png
